import {
	Outfit as OutfitFont,
	Ovo as OvoFont,
	Playfair_Display as PlayfairFont,
} from "next/font/google";
import "./globals.css";

// Load all fonts with CSS variables
const outfit = OutfitFont({
	subsets: ["latin"],
	weight: ["400", "500", "600", "700"],
	variable: "--font-outfit",
});

const ovo = OvoFont({
	subsets: ["latin"],
	weight: ["400"],
	variable: "--font-ovo",
});

const playfair = PlayfairFont({
	subsets: ["latin"],
	variable: "--font-playfair",
});

export const metadata = {
	title: "Portfolio - CodeForgeGrowth",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en" className="scroll-smooth">
			<body
				className={`${outfit.variable} ${ovo.variable} ${playfair.variable} antialiased leading-8 overflow-x-hidden`}
			>
				{children}
			</body>
		</html>
	);
}
